name: hydroman
description: "Smart Water Reminder App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^19.0.0
  fl_chart: ^0.70.2
  intl: ^0.20.2
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  uuid: ^4.5.1
  permission_handler: ^11.3.1
  google_mobile_ads: ^5.3.0
  http: ^1.3.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/splash.png"
  android: true
  ios: true
  android_12:
    color: "#ffffff"
    image: "assets/splash.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/splash.png
